### ISSUE TITLE
astype interface consolidates all blocks by default

### ISSUE THREAD

**Issue by chaburkland** [static-frame/static-frame#560]
**Description**

When you use the astype interface on a frame, `consolidate_blocks` is set to True by default.

This is not ideal, as no other interface that exposes that paramter defaults to True, and, this means that whenever you astype a frame, there is a decent chance you will re-consolidate many existing columns, thus loosing the reusability of the underlying blocks.

My suggestion is that for the 1.0 release:

1. `consolidate_blocks` defaults to False
2. Regardless of what `consolidate_blocks` is set to, the selection that is being astyped will be consolidated. So for example, if I have a frame with the following block structure:

8 columns (4 float, 4 int), already consolidated

if `frame.astype[frame.dtypes==int](float, consolidate_blocks=False)` then:
- the resulting frame will maintain the original float block, and it will contain another float block for what was retyped.

if `frame.astype[frame.dtypes==int](float, consolidate_blocks=True)` then:
- the resulting frame will only have one float block.

**Comment by flexatone** [comment]
Thanks for this issue and your suggestions. 

I have made the change to default `consolidate_blocks` to `False`; this will be in the 1.0 release.

Regarding consolidating the target of the astype, this is made a little complicated by the design of the functions that implement astype. In particular, the are designed to do a single pass through the underlying blocks and targets, as typing what is needed as encountered. Trying to isolate contiguous blocks that are being astyped to the same type, and consolidate just those, is a little awkward, and may be more expensive than the present implementation.

For these reasons I think it is best to create a `consolidate[]` interface that lets users explicitly consolidate a region of columns. I will create an issue for that feature.
