### ISSUE TITLE
The docstring for Frame.relabel's 'columns' argument is equal to that of its 'index' argument

### ISSUE THREAD

**Issue by eli-b** [static-frame/static-frame#640]
**Description**

The docstring for Frame.relabel's 'columns' argument is equal to that of its 'index' argument.

**Example**

The documentation for both parameters is ```"One of the following types, used to create a new ``Index`` with the same size as the previous index. (a) A mapping (as a dictionary or ``Series``), used to lookup and transform the labels in the previous index. Previous labels not found in the mapping will be reused. (b) A function, returning a hashable, that is applied to each label in the previous index. (c) The ``IndexAutoFactory`` type, to apply an auto-incremented integer index. (d) An index initializer, i.e., either an iterable of hashables or an ``Index`` instance."```. This seems incorrect for the `columns` argument since it does not seem to cause a new index to be created.

**Platform**

All platforms. Mine is:
```
platform           Linux-5.13.0-52-generic-x86_64-with-glibc2.34
sys.version        3.9.7 (default, Sep 10 2021, 14:59:43) [GCC 11.2.0]
static-frame       0.9.16
numpy              1.23.3
pandas             1.5.0
```

**Comment by flexatone** [comment]
Many thanks for isolating this inconsistency. The next publication of the docs will correct this.
