### ISSUE TITLE
Better Error Message/Special Handling for `Series.isna()` when it contains SF objects

### ISSUE THREAD

**Issue by chaburkland** [static-frame/static-frame#739]
**Description**

Series/Frames can contain SF containers. If they do, and `.isna()`, `.dropna()`, etc... is called, an unhelpful error message is printed:

```
ValueError: The truth value of a container is ambiguous. For a truthy indicator of non-empty status, use the `size` attribute.
```

It's possible that adding special handling in the na-checking code would be too detrimental to overall performance, in which case, I think maybe a better error message should be created

**Example**

For example, I was attempting to search through a yarn for any frames that contained object dtype columns.

```python
# This fails!
yarn.iter_element().apply(lambda f: f if (f.dtypes==object).any() else None).dropna()
```

I ended up having to use:
```python
sel = yarn.iter_element().apply(lambda f: (f.dtypes==object).any())
yarn[sel]
```
To a newer user of Static-Frame though, I imagine this alternative approach would not be obvious.

**Platform**
```python
<Series: platform>
<Index>
platform           Linux-5.4.0-137-generic-x86_64-with-glibc2.29
sys.version        3.8.12 (default, Jan 12 2023, 12:05:15) [GCC 9.4.0]
static-frame       1.2.2
numpy              1.19.2
pandas             0.25.3
xlsxwriter         1.1.5
openpyxl           3.0.9
xarray             <ModuleNotFoundError>
tables             3.6.1
pyarrow            0.17.0
msgpack            (1, 0, 0)
msgpack_numpy      None
<<U13>             <object>
```

**Comment by flexatone** [comment]
Many thanks for identifying this issue. The core problem is, in `isna()` identification, the handling of object arrays that might contain elements that raise on `__bool__()`. This will be corrected in the associated PR.
