### ISSUE TITLE
Offline docs page consumes almost 2GB RAM

### ISSUE THREAD

**Issue by 4l1fe** [static-frame/static-frame#762]
Just figured out that the documentation is signle-page of ~30MB.

I don't know why my browser renders it at so big cost ~2GB RAM.

Any plans on improving docs, making it mupltile-page?

**Comment by flexatone** [comment]
Thanks for asking. Can you let me know what page you are referring to? The API docs are grouped by container and category, so I would not expect any single page should be that big. For example, these are the docs for `Frame` attributes:

https://static-frame.readthedocs.io/en/latest/api_detail/frame-attribute.html

**Comment by flexatone** [comment]
Ah, I see what you mean! I was not aware ReadTheDocs was doing that. Let me see if I can configure this to use the same layout as the online docs.

**Comment by flexatone** [comment]
Hi @4l1fe . I do not seem to be able to configure this in ReadTheDocs: it appears to be an unfortunate default in ReadTheDocs.

Another option, if you pull the code and have an environment based around "requirements-dev.txt", is to just build the docs locally. You can do this by running `doc/build_doc.py` from the repo.

I am happy to assist if you need help building the docs locally. I will close this issue for now but feel free to reopen if needed.

**Comment by 4l1fe** [comment]
Ok, i'll try to build it up.

I've seen a couple of times other docs built up as a single page as well.
