### ISSUE TITLE
via_fill_value with IndexHierarchy

### ISSUE THREAD

**Issue by ForeverWintr** [static-frame/static-frame#771]
**Description**

The behavior of `via_fill_value` with IndexHierarchy is a little strange at the moment. I'm not sure what the right behavior is, as it could be difficult to apply fill_value when a partial index is specified, but I wanted to make note of it.

**Example**

Given this frame:
```python
f2 = sf.Frame.from_element(1, index=sf.IndexHierarchy.from_labels([[1, 2], [3, 4]]), columns=['a', 'b'])
<Frame>
<Index>                  a       b       <<U1>
<IndexHierarchy>
1                2       1       1
3                4       1       1
<int64>          <int64> <int64> <int64>
```
This works as expected:

```python
f2.via_fill_value(0).loc[sf.HLoc[1, 2]]
<Series: (1, 2)>
<Index>
a                1
b                1
<<U1>            <int64>
```

But attempting to select with a partial HLoc produces a square frame where the columns are propagated to the index. 

```python
f2.via_fill_value(0).loc[sf.HLoc[1, :]]
<Frame>
<Index> a       b       <<U1>
<Index>
a       0       0
b       0       0
<<U1>   <int64> <int64>
```

As that's a valid selection, I would expect it to return a result.

Here is another example, showing a selection without then with hloc:
```python
f2.loc[sf.HLoc[[1, 3]]]
<Frame>
<Index>                  a       b       <<U1>
<IndexHierarchy>
1                2       1       1
3                4       1       1
<int64>          <int64> <int64> <int64>

f2.via_fill_value(0).loc[sf.HLoc[[1, 3]]]
<Frame>
<Index> a       b       <<U1>
<Index>
a       0       0
b       0       0
<<U1>   <int64> <int64>
```

There are however more complicated scenarios for which I'm not sure of the right behavior. For example, when `HLoc` contains a partial match, e.g., `f2.loc[sf.HLoc[[1, 4]]]`.

**Platform**

Run the following function (static-frame >= 0.8.1) and provide the results to define your platform and environment:

```python
>>> import static_frame as sf
>>> sf.Platform.display()
<Series: platform>
<Index>
platform           Linux-5.19.0-38-generic-x86_64-with
sys.version        3.8.12 (default, Mar 31 2023, 10:54:28) [GCC 11.3.0]
static-frame       1.3.1
numpy              1.19.5
pandas             1.4.4
xlsxwriter         1.2.2
openpyxl           3.0.9
xarray             <ModuleNotFoundError>
tables             3.6.1
pyarrow            0.17.0
msgpack            (1, 0, 0)
msgpack_numpy      None
<<U13>             <object>
```

**Comment by flexatone** [comment]
Many thanks, @ForeverWintr , for isolating this issue. This will be corrected in the 2.15.1 release.
