### ISSUE TITLE
Inconsistent `nan` arithmetic between `Frame` and `Series`

### ISSUE THREAD

**Issue by philipmassouh** [static-frame/static-frame#816]
**Description**

`nan` is treated as zero when summing frames, but will propagate when summing series.

**Example**

Provide an interactive Python session, or Python code, to demonstrate the issue. Please keep example data to a minimum.

```
>>> import static_frame as sf
>>> import numpy as np
>>> f = sf.Frame.from_dict(
...     dict(
...         a=(0.1, np.nan),
...         b=(np.nan, 0.5),
...     )
... )
>>> f
<Frame>
<Index> a         b         <<U1>
<Index>
0       0.1       nan
1       nan       0.5
<int64> <float64> <float64>
>>> f["a"] + f["b"]
<Series>
<Index>
0        nan
1        nan
<int64>  <float64>
>>> f.sum(axis=1)
<Series>
<Index>
0        0.1
1        0.5
<int64>  <float64>
```

**Platform**
```python
>>> sf.Platform.display()
<Series: platform>
<Index>
platform           Linux-5.15.0-76-generic-x86_64-with-glibc2.29
sys.version        3.8.12 (default, Feb  7 2023, 20:55:02) [GCC 9.4.0]
static-frame       1.4.4
numpy              1.24.3
pandas             1.5.3
xlsxwriter         3.1.0
openpyxl           3.0.9
xarray             <ModuleNotFoundError>
tables             3.8.0
pyarrow            0.17.1
msgpack            (1, 0, 0)
msgpack_numpy      None
<<U13>             <object>
```

**Comment by chaburkland** [comment]
I think this is intentional behavior.
You can acheive `f['a'] + f['b']` if you pass in the `skipna` argument:
```python
>>> f.sum(axis=1, skipna=False)                                                                                                                                                                                                                                    
<Series>
<Index>
0        nan
1        nan
<int64>  <float64>
```
Is you hope that the default `skipna` argument changes? Because I feel there is a good reason to keep them different

**Comment by flexatone** [comment]
Thanks for posting this question, @philipmassouh 

As @chaburkland  points out, in the case of functions, the `skipna` parameter defaults to `False`; you can set this to `True` if desirable. That the default is `True` is certainly debatable, however I was inclined to support what appears the most common use cases and common usage in Pandas. Note that these functions are often "reducing" methods (sum, mean, median, std, etc.) where dropping NaNs is very practical.

For usage with operators, NaNs are propagated. The intuition for this might be (a) element wise operations with NumPy behave the same and (b) these are not "reducing" operations (like sum, mean, etc), but are element-wise, labelled operations. 

A agree that a more consistent approach would  be to have NaNs in all cases propagate by default; my impression, however, is that it is just far less than practical for the "reducing" methods where NaNs are so-commonly skipped.

Note also that, in these reducing methods, NaN is not treated as zero, but is actually removed before calculation. This is not clear in the case of `sum` but is in the case of `mean`:

```python
>>> s1 = sf.Series([3, 3, 3, np.nan])                                           
>>> s1.mean()                                                                   
3.0
>>> s1.fillna(0).mean()                                                         
2.25
```

**Comment by philipmassouh** [comment]
@flexatone @chaburkland thank you both for the responses. For `mean()`, I would expect it to return `nan` and for a `nanmean`/`mean(skipna=True)` to return 3.0. 

Looking at our current uses, the defaults are in close alignment with our current use case; even though I think it is better to propagate `nan`, I am not sure it is worth breaking backwards compatibility.
