### ISSUE TITLE
Type hints for Series

### ISSUE THREAD

**Issue by olivercoleman-switchdin** [static-frame/static-frame#818]
**Description**

Would be great to have type hints for Series.

**Example**

```python
my_series: sf.Series[float] = sf.Series([1,2,3], dtype=float)
my_other_series: sf.Series[str] = my_series  # should raise an error in type checkers.
```

**Platform**
```
<Series: platform>
<Index>
platform           Linux-5.15.0-76-generic-x86_64-with-glibc2.36
sys.version        3.11.4 (main, Jul  4 2023, 05:35:05) [GCC 12.2.0]
static-frame       1.4.6
numpy              1.25.1
pandas             <ModuleNotFoundError>
xlsxwriter         <ModuleNotFoundError>
openpyxl           <ModuleNotFoundError>
xarray             <ModuleNotFoundError>
tables             <ModuleNotFoundError>
pyarrow            <ModuleNotFoundError>
msgpack            <ModuleNotFoundError>
msgpack_numpy      <ModuleNotFoundError>
<<U13>             <object>
```

**Comment by flexatone** [comment]
Many thanks for this suggestion. I plan to explore this in the future.

**Comment by flexatone** [comment]
Thanks again for this suggestion. StaticFrame 2.0 will introduce fully generic `Series`, `Frame`, and many other containers. Unlike what is done with the `pandas-stubs`, the StaticFrame `Series` will be generic by both the index and the values. So you will be able to have hints like the following:

```python
s1: sf.Series[sf.Index[np.str_], np.float64]
s2: sf.Series[sf.IndexDate, np.int64]
```

More on this in a forthcoming article describing these features. StaticFrame 2.0 will be released in a few weeks.
