### ISSUE TITLE
`mypy --strict` errors on some `sf.Series.from_dict` calls

### ISSUE THREAD

**Issue by gettodaze** [static-frame/static-frame#833]
**Description**
`mypy --strict` (version 1.4.1) gives me an error when passing in the a dictionary typed as `dict[str, float]` into `sf.Series.from_dict`. I have not tested other mypy versions.

From [the explanation here](https://github.com/python/mypy/issues/8293#issuecomment-577084412), it seems that `mypy --strict` expects dictionary keys to be **invariant**, thus giving an error when passed `sf.Series.from_dict` is passed a dictionary with keys that are not of the exact type `tp.Hashable`. In other words, even though `sf.Series.from_dict` takes in any dictionary (with hashable keys), `mypy --strict` will not accept any subclasses of `tp.Hashable` as they argument's keys .

Error:
`Argument 1 to "from_dict" of "Series" has incompatible type "Dict[str, float]"; expected "Dict[Hashable, Any]"  [arg-type]`

Are there any good workarounds for this?

**Example**

```python
# sf_from_dict.py
import typing as tp

import static_frame as sf

s = sf.Series.from_dict({"a": 1})

d: tp.Dict[str, float] = {"a": 1}
s2 = sf.Series.from_dict(d)
```

```
# command line
❯ mypy sf_from_dict.py --strict
sf_from_dict.py:8: error: Argument 1 to "from_dict" of "Series" has incompatible type "Dict[str, float]"; expected "Dict[Hashable, Any]"  [arg-type]
Found 1 error in 1 file (checked 1 source file)
❯ mypy sf_from_dict.py -V
mypy 1.4.1 (compiled: yes)
```

**Platform**

Run the following function (static-frame >= 0.8.1) and provide the results to define your platform and environment:

```python
>>> import static_frame as sf
>>> sf.Platform.display()
In [3]: sf.Platform.display()                                                                                                                                                                                      
Out[3]: 
<Series: platform>
<Index>
platform           Linux-5.15.0-79-generic-x86_64-with-glibc2.29
sys.version        3.8.12 (default, Jul 28 2023, 12:44:26) [GCC 9.4.0]
static-frame       1.5.0
numpy              1.24.3
pandas             1.5.3
xlsxwriter         3.1.0
openpyxl           3.0.9
xarray             <ModuleNotFoundError>
tables             3.8.0
pyarrow            0.17.1
msgpack            (1, 0, 0)
msgpack_numpy      None
<<U13>             <object>
```

**Comment by gettodaze** [comment]
I get the same error with mypy `1.5.1`.

```
>>> sf.Platform.display()
<Series: platform>
<Index>
platform           Linux-5.15.0-79-generic-x86_64-with-glibc2.29
sys.version        3.8.12 (default, Jul 28 2023, 12:44:26) [GCC 9.4.0]
static-frame       1.6.0
numpy              1.24.4
pandas             <ModuleNotFoundError>
xlsxwriter         <ModuleNotFoundError>
openpyxl           <ModuleNotFoundError>
xarray             <ModuleNotFoundError>
tables             <ModuleNotFoundError>
pyarrow            <ModuleNotFoundError>
msgpack            <ModuleNotFoundError>
msgpack_numpy      <ModuleNotFoundError>
<<U13>             <object>
>>> 
❯ mypy -V
mypy 1.5.1 (compiled: yes)
❯ mypy sf_from_dict.py --strict
sf_from_dict.py:8: error: Argument 1 to "from_dict" of "Series" has incompatible type "Dict[str, float]"; expected "Dict[Hashable, Any]"  [arg-type]
Found 1 error in 1 file (checked 1 source file)
```

**Comment by flexatone** [comment]
Many thanks for isolating this issue. 

While I have completely replaced my usage of `tp.Hashable` with a better union type, as you point out, this issue has to do with invariance. While making the interface take a `tp.Mapping` is an improvement, it also does not solve this issue.

The only solution I found is to make the interface take a `tp.Mapping[tp.Any, tp.Any]`.

I have done this for all dictionary inputs in constructors; this will be part of the 1.6.4 release.
