### ISSUE TITLE
Improve Precision of Type Hints

### ISSUE THREAD

**Issue by michaeljpeters** [static-frame/static-frame#835]
Some type hints (especially those involving slicing frames/series) could be made more precise. Likely could be done using some form of `tp.overload`

Describe the issue.

`Frame[...]` -> `Frame / Series`
- Frame if list
- Series otherwise

`Series[...]` -> `Series / <type>`
- Series if list
- \<type\> otherwise

`FrameGO[...]` -> `FrameGO / Series` (currently gives Frame / Series)
- FrameGO if list
- Series otherwise
- NOTE: currently is acting like it returns a Frame, is this correct?

`Frame.iloc[int]` -> `Series`
- Currently typed to return a Frame

`Series.iloc[int]` -> `<type>`
- Currently typed to return a Series

`Frame.from_records_items()` should accept `dict_items`
- Likely since using Iterator instead of Iterable

`Frame.astype(str)` should be accepted
- This works properly in Series

**Platform**

Run the following function (static-frame >= 0.8.1) and provide the results to define your platform and environment:

```python
>>> import static_frame as sf
>>> sf.Platform.display()
<Series: platform>
<Index>
platform           Linux-5.15.0-79-generic-x86_64-with-glibc2.29
sys.version        3.8.12 (default, Apr  4 2023, 11:01:57) [GCC 9.4.0]
static-frame       1.6.0
numpy              1.24.3
pandas             1.5.3
xlsxwriter         3.1.0
openpyxl           3.0.9
xarray             <ModuleNotFoundError>
tables             3.8.0
pyarrow            0.17.1
msgpack            (1, 0, 0)
msgpack_numpy      None
<<U13>             <object>
```

**Comment by flexatone** [comment]
All of these issues have been addressed and will be part of the 1.6.4 release.
