### ISSUE TITLE
In `WWW`, quote / sanitize URLs before passing to `urlopen`

### ISSUE THREAD

**Issue by flexatone** [static-frame/static-frame#853]
https://docs.python.org/3/library/urllib.parse.html#url-quoting

**Comment by alfiq** [comment]
Hello,
if you want you can assign it to me, I can try and fix it.

**Comment by flexatone** [comment]
@alfiq : Many thanks for offering to work on this.

The fix should be pretty straight forward, we just need to call `urllib.parse.quote` in the appropriate places in www.py when given raw user URLs as string. The motivating example is a URL with spaces in it (where spaces should be encoded with %20).
