### ISSUE TITLE
Support for generic type variables in loc, iloc, __getitem__, ...

### ISSUE THREAD

**Issue by olivercoleman-switchdin** [static-frame/static-frame#865]
I was surprised to discover that new (and very much appreciated!) generic type variables for Series do not extend to the `loc`, `iloc`, `__getitem__`, etc interfaces. Is this on the roadmap? For example, I was expecting the type hint of `x` below to be `np.int64`:
```python
import static_frame as sf
import numpy as np
series:sf.Series[sf.Index[np.int64], np.int64] = sf.Series([1, 2, 3])
x = series.iloc[1]
```

**Comment by flexatone** [comment]
Thanks, @olivercoleman-switchdin , for asking. Yes, there is much more to do to flesh out the power of generic specification going forward in the 2.0 series. The case you have identified can be implemented with `typing.overload` and is a good for me to work on first. I will explore a PR.

**Comment by flexatone** [comment]
Thanks again for isolating this issue. I have corrected this behavior for 1D containers. The example you provide will now properly show `x` as an `np.int64`. This will be part of the 2.3 release.
