### ISSUE TITLE
Docs - Print Frame Before Methods Are Executed

### ISSUE THREAD

**Issue by michaeljpeters** [static-frame/static-frame#878]
Sometimes, in the docs, it is challenging to understand the contents of a frame before a method is called. For example, in cumprod, the frame is only printed after .cumprod is applied to the frame.

![image](https://github.com/static-frame/static-frame/assets/113062340/e9d33867-84bd-49cb-a960-69ff4a249357)

Describe the feature.

It would be useful to update the docs to always print the frame before the method is called.

![image](https://github.com/static-frame/static-frame/assets/113062340/1ec6e460-647f-4350-933b-df53688dfe87)

**Platform**

Run the following function (static-frame >= 0.8.1) and provide the results to define your platform and environment:

```python
>>> import static_frame as sf
>>> sf.Platform.display()
<Series: platform>
<Index>
platform           Linux-5.15.0-91-generic-x86_64-with-glibc2.29
sys.version        3.8.12 (default, Apr  4 2023, 11:01:57) [GCC 9.4.0]
static-frame       2.0.1
numpy              1.24.3
pandas             1.5.3
xlsxwriter         3.1.0
openpyxl           3.0.9
xarray             <ModuleNotFoundError>
tables             3.8.0
pyarrow            0.17.1
msgpack            (1, 0, 0)
msgpack_numpy      None
<<U13>             <object>
```

**Comment by flexatone** [comment]
Thanks for this suggestion; I will begin adding these more consistently.
