### ISSUE TITLE
NPY/NPZ should be more resilient to non-filepaths

### ISSUE THREAD

**Issue by chaburkland** [static-frame/static-frame#903]
https://github.com/static-frame/static-frame/blob/b1b55b491ed6bfea2bad12d264fca18594daf5a0/static_frame/core/archive_npy.py#L768

This branch fails when the provided file-like object is neither `io.BytesIO` nor a filepath. However, I would expect this case to work correctly:

```python
with open(fp, "wb") as f:
    frame.to_npz(f)
```

**Comment by flexatone** [comment]
Interesting; I will investigate!

**Comment by flexatone** [comment]
Thanks, @chaburkland , for posting this. Can you provide an example that fails? The case you suggest does work as an open binary file is an instance of `io.IOBase`.
```
>>> file = open('/tmp/f.npz', 'wb')
>>> import io
>>> isinstance(file, io.IOBase)
True

>>> f = sf.Frame.from_records([[1, 2, np.nan], [3, np.nan, np.nan]])
>>> f.to_npz(file)
>>> file.close()

>>> sf.Frame.from_npz('/tmp/f.npz')
<Frame>
<Index> 0       1         2         <int64>
<Index>
0       1       2.0       nan
1       3       nan       nan
<int64> <int64> <float64> <float64>
```

**Comment by flexatone** [comment]
@chaburkland : please check if you can reproduce an error regarding this.

**Comment by chaburkland** [comment]
This issue is not present on more recent versions of static-frame. The issue is that my version of code was doing a check of `isinstance(f, BytesIO)`, and the newer code has `isinstance(f, io.IOBase)`, which is the fix I had envisioned
