### ISSUE TITLE
Allow `sf.Yarn` to support non-labeled buses when `retain_labels=False`

### ISSUE THREAD

**Issue by chaburkland** [static-frame/static-frame#916]
**Description**

When constructing a yarn using `sf.Yarn.from_buses`, even when `retain_labels=False`, you will get an error if all the buses share the same name.

I think this is not ideal, since the user specified they do not care about the bus names, only about the contents of the buses. As such, I think `sf.Yarn` should manage placeholder names for the buses internally (likely just `0, 1, ..., len(buses) - 1`), instead of failing if the buses do not have unique names.

**Example**

```python
import frame_fixtures as ff
import static_frame as sf

ff.parse("s(3,3)")
b1 = sf.Bus.from_frames((ff.parse("s(3,3)").rename("f1"),))
b2 = sf.Bus.from_frames((ff.parse("s(3,3)").rename("f2"),))
b3 = sf.Bus.from_frames((ff.parse("s(3,3)").rename("f3"),))

sf.Yarn.from_buses((b1, b2, b3), retain_labels=False) # Fails! I would expect it to look the the `yarn` below

yarn = sf.Yarn.from_buses(
    (
        b1.rename("i do not care"),
        b2.rename("about these"),
        b3.rename("placeholder labels"),
    ),
    retain_labels=False,
)
"""
<Yarn>
<Index>
f1      Frame
f2      Frame
f3      Frame
<<U2>   <object>
"""
```

**Platform**

Run the following function (static-frame >= 0.8.1) and provide the results to define your platform and environment:

```python
<Series: platform>
<Index>
platform           Linux-5.4.0-174-generic-x86_64-with-glibc2.31
sys.version        3.11.4 (main, Feb  7 2024, 10:52:06) [GCC 9.4.0]
static-frame       2.2.3
numpy              1.24.3
pandas             1.5.3
xlsxwriter         3.1.0
openpyxl           3.0.9
xarray             <ModuleNotFoundError>
tables             3.8.0
pyarrow            12.0.1
msgpack            (1, 0, 0)
msgpack_numpy      None
<<U13>             <object>
```

**Comment by flexatone** [comment]
This is a great complement to #917 . As I think we are building the indices without the context of the setting of `retain_labels`. In this case, as other, I fully support this change.
