### ISSUE TITLE
Add `Yarn.sort_index`

### ISSUE THREAD

**Issue by chaburkland** [static-frame/static-frame#920]
See title :upside_down_face:

**Comment by flexatone** [comment]
Thanks for the issue, but if a sort implies that a `Frame` in one `Bus` should move to another `Bus`, how would that work?

**Comment by flexatone** [comment]
This could be implemented with an intermediary 1D mapping array, whereby selections on the public index are converted to selections within the internal `IndexHierarchy` by passing through this mapping array. This will reduce performance in some cases as slices will be reduced to a Boolean selection, but should work.
