### ISSUE TITLE
add index.via_dt.year_quarter interface

### ISSUE THREAD

**Issue by AlanMLin** [static-frame/static-frame#957]
**Description**

Could you please add index.via_dt.year_quarter interface, similar to index.via_dt.year and index.via_dt.year_month interfaces?

**Example**

ipdb> frame.index.via_dt.year_quarter
array(['2017-1', '2017-2', '2017-3','2017-4', ..., '2024-1', '2024-2'], dtype='<U7')

```python

```

**Platform**

Run the following function (static-frame >= 0.8.1) and provide the results to define your platform and environment:

```python
>>> import static_frame as sf
>>> sf.Platform.display()
```

**Comment by flexatone** [comment]
@AlanMLin : Thanks for this request.

The implementation is nearly complete but I wonder about the string representation. I fear that using just an integer for quarter, i.e., "2017-1", looks too much like a truncated year month string "2017-11". Of course, "2024-2" is clearly not a truncated year-month string, but the issue remains. There does not seem to be a formal standard for this representation.

Two options:
1. Keep the property interface and use a "Q" prefix, i.e., "2017-Q1", "2024-Q2": this makes the string representation clearly distinct from a year month string.
2. Use a function interface and let the user provide a format string or other configuration.

Is the "Q" prefix practical, or do you have other suggestions?

**Comment by AlanMLin** [comment]
@flexatone thanks for looking into this. Option 1 "Q" prefix sounds pretty good.
