### ISSUE TITLE
Support selecting from an IndexHierarchy with `Hloc`

### ISSUE THREAD

**Issue by ForeverWintr** [static-frame/static-frame#971]
**Description**

You can select from a Series or Frame with an IndexHierarchy using HLoc, but when all you care about is the index, it would be nice to be able to select from the index directly. 

**Example**

I would like to be able to do this:
```python
idx = sf.IndexHierarchy.from_labels([('a', 1), ('a', 2), ('b', 3)])
print(idx[sf.HLoc['a']])
```

I imagine the result would be the same as:

```python
print(idx[:2])
```

Currently, the only way I know of to accomplish this is to create a temporary series/frame:

```python
print(sf.Series.from_element('', index=idx).loc[sf.HLoc['a']].index)
```

**Platform**

Run the following function (static-frame >= 0.8.1) and provide the results to define your platform and environment:

```python
>>> import static_frame as sf
>>> sf.Platform.display()
<Series: platform>
<Index>
platform           Linux-6.9.3-76060903-generic-x86_64-with-glibc2.35
sys.version        3.11.4 (main, Aug 14 2024, 15:47:04) [GCC 11.4.0]
static-frame       2.13.0
numpy              1.24.3
pandas             1.5.3
xlsxwriter         3.1.0
openpyxl           3.0.9
xarray             <ModuleNotFoundError>
tables             3.8.0
pyarrow            12.0.1
msgpack            None
msgpack_numpy      None
<<U13>             <object>
```

**Comment by ForeverWintr** [comment]
On a similar note, it would be nice to do `iter_group` with just an IndexHierarchy!

**Comment by chaburkland** [comment]
You can get this behavior by doing:
```python
>>> idx = sf.IndexHierarchy.from_labels([('a', 1), ('a', 2), ('b', 3)])
>>> idx.loc[sf.HLoc['a']]
```

I do see though that it's a bit strange that the `__getitem__` interface doesn't support `HLoc`. It probably should

**Comment by flexatone** [comment]
Thanks for asking about this functionality. On `Index` or `IndexHierarchy`, the `__getitem__` interfaces are iloc-style interfaces, not loc-style. There are a number of reasons, but in general, index are array-like.  Thus only integers, integer slices, and Boolean areas can be used with `__getitem__`. As @chaburkland  points out, using the `.loc` interface on an `IndexHierarchy` permits using the `HLoc` selector"

```python
>>> idx = sf.IndexHierarchy.from_labels([('a', 1), ('a', 2), ('b', 3)])
>>> idx .loc[sf.HLoc['a']]
<IndexHierarchy>
a                1
a                2
<<U1>            <int64>
```
