### ISSUE TITLE
Consider updating an error message for invalid assignment

### ISSUE THREAD

**Issue by chaburkland** [static-frame/static-frame#973]
**Description**

Many pandas users are familiar with the paradigm `s.loc[key] = value`. However, the failure message might be confusing to new SF users

**Example**
```python
'InterGetItemLocReduces' object does not support item assignment
```

My suggestion is to say something instead like `Direct item assignment is not supported. See the .assign interface for how to create modified`

At the very least, I would want to it to say `'Series' object does not support item assignment` (or Frame, etc...)

**Comment by flexatone** [comment]
Thanks for this great suggestion. Now you will get an informative `ImmutableTypeError`

```
>>> s = sf.Series(('a', 'b'))
>>> s.loc[0] = 'c'
static_frame.core.exception.ImmutableTypeError: Series is immutable; use `Series.assign.loc[0]('c')` to derive a modified container.
```
